# Generated by Django 4.2.7 on 2023-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id_movimiento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=20, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
                ('orden_compra', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=10, primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=20, null=True)),
                ('tipo_solicitud', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=20, null=True)),
                ('beneficiario', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
                ('programa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=30, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
