# Generated by Django 4.2.6 on 2023-11-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.BigIntegerField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(blank=True, max_length=20, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField(blank=True, unique=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=255)),
                ('clave', models.BigIntegerField(blank=True, max_length=5)),
                ('rol', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'temp_usuario',
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id_movimiento', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('id_usuario', models.FloatField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Web_app.producto')),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id_detalle_sol', models.FloatField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.FloatField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Web_app.producto')),
                ('id_solicitud', models.ForeignKey(blank=True, db_column='id_solicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Web_app.solicitud')),
            ],
            options={
                'db_table': 'detalle_solicitud',
            },
        ),
    ]
