# Generated by Django 4.2.6 on 2023-11-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
