# Generated by Django 4.2.6 on 2023-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
