# Generated by Django 4.2.7 on 2023-12-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0002_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=8),
        ),
    ]
