# Generated by Django 4.2.6 on 2023-11-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0003_producto_orden_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesolicitud',
            options={},
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='ruta_archivo',
            new_name='tipo_solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
