# Generated by Django 4.2.6 on 2023-11-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0004_alter_detallesolicitud_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientosinventario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='movimientosinventario',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, db_column='id_solicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Web_app.solicitud'),
        ),
    ]
