# Generated by Django 4.2.6 on 2023-11-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0005_remove_movimientosinventario_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosinventario',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Web_app.usuario'),
        ),
    ]
