# Generated by Django 4.2.6 on 2023-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0007_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
