# Generated by Django 4.2.7 on 2023-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0009_alter_usuario_clave_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='programa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
