# Generated by Django 4.2.7 on 2023-12-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0004_alter_usuario_clave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientosinventario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={},
        ),
    ]
