# Generated by Django 4.2.7 on 2023-12-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0010_alter_movimientosinventario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id_movimiento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('id_producto', models.ForeignKey('Producto', models.DO_NOTHING, db_column='id_producto', blank=True, null=True)),
                ('id_solicitud', models.ForeignKey('Solicitud', models.DO_NOTHING, db_column='id_solicitud', blank=True, null=True))                  
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
    ]
