# Generated by Django 4.2.7 on 2023-11-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0011_alter_solicitud_id_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosinventario',
            name='id_movimiento',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
