# Generated by Django 4.2.7 on 2023-12-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0012_movimientosinventario_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='detalle_solicitud',
            field=models.TextField(blank=True),
        ),
    ]
