# Generated by Django 4.2.7 on 2023-12-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0013_solicitud_detalle_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosinventario',
            name='proceso_completo',
            field=models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=10, null=True),
        ),
    ]
